
package Visao;
import Controllers.cursoontroller;
import Controllers.InstrutorController;
import Controllers.OfertaController;
import static DAO.Tabelas.Tabelas.curso;
import static DAO.Tabelas.Tabelas.instrutor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Oferta;
import modelo.Curso;
import modelo.Instrutor;

/**
 *
 * @author Sullyvan Marks
 */
public class NewJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    public NewJPanel1() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        NomeI = new javax.swing.JLabel();
        CPFI = new javax.swing.JLabel();
        EndI = new javax.swing.JLabel();
        CelI = new javax.swing.JLabel();
        CadastrarInstrutor = new javax.swing.JButton();
        InputNomeInstrutor = new javax.swing.JTextField();
        InputCPFInstrutor = new javax.swing.JTextField();
        InputEnderecoInstrutor = new javax.swing.JTextField();
        InputCelularInstrutor = new javax.swing.JTextField();
        IdI = new javax.swing.JLabel();
        InputIDInstrutor = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        InputBuscaInstrutor = new javax.swing.JTextField();
        BotaoBuscaInsrutor = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        DataF = new javax.swing.JLabel();
        NomeO = new javax.swing.JLabel();
        DataI = new javax.swing.JLabel();
        StatusO = new javax.swing.JLabel();
        InstrutorO = new javax.swing.JLabel();
        CadastrarOferta = new javax.swing.JButton();
        InputIDOferta = new javax.swing.JTextField();
        InputDataInicialOferta = new javax.swing.JTextField();
        InputDataFinalOferta = new javax.swing.JTextField();
        InputSituacaoOferta = new javax.swing.JTextField();
        InputIdInstrutorOferta = new javax.swing.JTextField();
        InputCursoOferta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InputBuscaOferta = new javax.swing.JTextField();
        BotaoBuscaOferta = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cursoL = new javax.swing.JLabel();
        ementaL = new javax.swing.JLabel();
        hourL = new javax.swing.JLabel();
        CadastrarCurso = new javax.swing.JButton();
        NomeInputCurso = new javax.swing.JTextField();
        InputEmentaCurso = new javax.swing.JTextField();
        InputCargaCurso = new javax.swing.JTextField();
        NomeO1 = new javax.swing.JLabel();
        InputIdCurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputBuscaCurso = new javax.swing.JTextField();
        BotaoBuscaCurso = new javax.swing.JButton();

        NomeI.setText("Nome:");

        CPFI.setText("CPF:");

        EndI.setText("Endereço:");

        CelI.setText("Celular");

        CadastrarInstrutor.setText("Cadastrar");
        CadastrarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarInstrutorActionPerformed(evt);
            }
        });

        InputNomeInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomeInstrutorActionPerformed(evt);
            }
        });

        IdI.setText("Id:");

        InputIDInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIDInstrutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastrarInstrutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeI)
                    .addComponent(CPFI)
                    .addComponent(EndI)
                    .addComponent(CelI)
                    .addComponent(IdI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputNomeInstrutor)
                            .addComponent(InputCPFInstrutor)
                            .addComponent(InputEnderecoInstrutor)
                            .addComponent(InputCelularInstrutor, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                        .addGap(189, 189, 189))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(InputIDInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeI)
                    .addComponent(InputNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFI)
                    .addComponent(InputCPFInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndI)
                    .addComponent(InputEnderecoInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelI)
                    .addComponent(InputCelularInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdI)
                    .addComponent(InputIDInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(CadastrarInstrutor)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Cadastrar novo Instrutor", jPanel4);

        jLabel3.setText("Digite o nome do instrutor que você deseja consulltar:");

        InputBuscaInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputBuscaInstrutorActionPerformed(evt);
            }
        });

        BotaoBuscaInsrutor.setText("Buscar");
        BotaoBuscaInsrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaInsrutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(InputBuscaInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BotaoBuscaInsrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoBuscaInsrutor, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(InputBuscaInstrutor))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Consulta", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane1.addTab("Instrutor", jPanel1);

        DataF.setText("Data Final:");

        NomeO.setText("Id:");

        DataI.setText("Data Inicial:");

        StatusO.setText("Situação Oferta:");

        InstrutorO.setText("Instrutor:");

        CadastrarOferta.setText("Cadastrar");
        CadastrarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarOfertaActionPerformed(evt);
            }
        });

        InputIDOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIDOfertaActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadastrarOferta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(NomeO)
                                            .addGap(88, 88, 88)
                                            .addComponent(InputIDOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(StatusO)
                                                .addComponent(jLabel4))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(InputCursoOferta)
                                                .addComponent(InputDataFinalOferta)
                                                .addComponent(InputDataInicialOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(InputSituacaoOferta, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(InstrutorO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InputIdInstrutorOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 155, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataI)
                            .addComponent(DataF))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeO)
                    .addComponent(InputIDOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataI)
                    .addComponent(InputDataInicialOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataF)
                    .addComponent(InputDataFinalOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusO)
                    .addComponent(InputSituacaoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCursoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstrutorO)
                    .addComponent(InputIdInstrutorOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(CadastrarOferta)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Cadastrar nova oferta", jPanel3);

        jLabel2.setText("Digite o nome da oferta que você deseja consulltar:");

        InputBuscaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputBuscaOfertaActionPerformed(evt);
            }
        });

        BotaoBuscaOferta.setText("Buscar");
        BotaoBuscaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaOfertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(InputBuscaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BotaoBuscaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoBuscaOferta, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(InputBuscaOferta))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Consultar", jPanel7);

        jTabbedPane1.addTab("Oferta", jTabbedPane3);

        cursoL.setText("Nome:");

        ementaL.setText("Ementa:");

        hourL.setText("Carga Horária:");

        CadastrarCurso.setText("Cadastrar");
        CadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarCursoActionPerformed(evt);
            }
        });

        NomeO1.setText("Id:");

        InputIdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIdCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(hourL)
                                .addGap(18, 18, 18)
                                .addComponent(InputCargaCurso))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ementaL)
                                .addGap(18, 18, 18)
                                .addComponent(InputEmentaCurso))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cursoL)
                                .addGap(27, 27, 27)
                                .addComponent(NomeInputCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addComponent(NomeO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NomeO1)
                        .addComponent(InputIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cursoL)
                        .addComponent(NomeInputCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ementaL)
                    .addComponent(InputEmentaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourL)
                    .addComponent(InputCargaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CadastrarCurso)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cadastrar novo curso", jPanel2);

        jLabel1.setText("Digite o nome do curso que você deseja consulltar:");

        InputBuscaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputBuscaCursoActionPerformed(evt);
            }
        });

        BotaoBuscaCurso.setText("Buscar");
        BotaoBuscaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(InputBuscaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BotaoBuscaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoBuscaCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(InputBuscaCurso))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        jTabbedPane2.addTab("Consultar", jScrollPane1);

        jTabbedPane1.addTab("Curso", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        });
    }
    
    private void CadastrarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarOfertaActionPerformed
        OfertaController controller;
        try {
            controller = new OfertaController();

            long id = Integer.parseInt(InputIDOferta.getText());
            String dataInicial = InputDataInicialOferta.getText();
            String dataFinal = InputDataFinalOferta.getText();
            int status = Integer.parseInt(InputSituacaoOferta.getText());
            long curso = Integer.parseInt(InputCursoOferta.getText());
            long instrutor = Integer.parseInt(InputIdInstrutorOferta.getText());
            
            
            Oferta Oferta = new Oferta(id, dataInicial, dataFinal, status, curso, instrutor);
            if(controller.salvar(Oferta)){
                System.out.println("cadastrado com sucesso!");
                InputIDOferta.setText("");
                InputDataInicialOferta.setText("");
                InputDataFinalOferta.setText("");
                InputSituacaoOferta.setText("");
                InputCursoOferta.setText("");
                InputIdInstrutorOferta.setText("");
                
            } else {
                System.out.println("Ocorreu um erro ao tentar cadastrar.");
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewJPanel1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ocorreu um erro ao tentar cadastrar.");
        }
    }//GEN-LAST:event_CadastrarOfertaActionPerformed

    private void CadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarCursoActionPerformed
        cursoontroller controller;
        try {
            controller = new cursoontroller();

            long id = Integer.parseInt(InputIdCurso.getText());
            String nome = NomeInputCurso.getText();
            String ementa = InputEmentaCurso.getText();
            String cargaHoraria = InputCargaCurso.getText();
            
            
            Curso Curso = new Curso(id, nome, ementa, cargaHoraria);
            if(controller.salvar(Curso)){
                System.out.println("cadastrado com sucesso!");
                InputIdCurso.setText("");
                NomeInputCurso.setText("");
                InputEmentaCurso.setText("");
                InputCargaCurso.setText("");
                
            } else {
                System.out.println("Ocorreu um erro ao tentar cadastrar.");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewJPanel1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ocorreu um erro ao tentar cadastrar.");
        }
    }//GEN-LAST:event_CadastrarCursoActionPerformed

    private void InputIDOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIDOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIDOfertaActionPerformed

    private void InputBuscaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputBuscaCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputBuscaCursoActionPerformed

    private void InputBuscaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputBuscaOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputBuscaOfertaActionPerformed

    private void InputNomeInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomeInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNomeInstrutorActionPerformed

    private void CadastrarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarInstrutorActionPerformed
        InstrutorController controller;
        try {
            controller = new InstrutorController();

            long id = Integer.parseInt(InputIDInstrutor.getText());
            String nome = InputNomeInstrutor.getText();
            String cpf = InputCPFInstrutor.getText();
            String endereco = InputEnderecoInstrutor.getText();
            String celular = InputCelularInstrutor.getText();
            
            Instrutor Instrutor = new Instrutor(id, nome, cpf, endereco, celular);
            if(controller.salvar(Instrutor)){
                System.out.println("cadastrado com sucesso!");
                InputIDInstrutor.setText("");
                InputNomeInstrutor.setText("");
                InputCPFInstrutor.setText("");
                InputEnderecoInstrutor.setText("");
                InputCelularInstrutor.setText("");
                
            } else {
                System.out.println("Ocorreu um erro ao tentar cadastrar.");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewJPanel1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ocorreu um erro ao tentar cadastrar.");
        }
    }//GEN-LAST:event_CadastrarInstrutorActionPerformed

    private void InputBuscaInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputBuscaInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputBuscaInstrutorActionPerformed

    private void InputIDInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIDInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIDInstrutorActionPerformed

    private void InputIdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIdCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIdCursoActionPerformed

    private void BotaoBuscaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoBuscaOfertaActionPerformed

    private void BotaoBuscaInsrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaInsrutorActionPerformed
           String consultarNome = InputBuscaInstrutor.getText();

            InstrutorController controller;
            try {
                controller = new InstrutorController();
                
                List Instrutor = controller.consultar(consultarNome);
                List<String> instrutorLido = new ArrayList();

                   instrutorLido.forEach((String instrutor) -> {
                   instrutorLido.add(Instrutor.toString());
               });
                System.out.println(Instrutor);
                System.out.println("Buscado com sucesso");
            } catch (ClassNotFoundException ex) {
                System.out.println("opa, meu bom, parece que alguma classe deu ruim");
            } catch (SQLException ex) {
                 System.out.println("opa, meu bom, parece que o Sql deu ruim");
            }
        
    }//GEN-LAST:event_BotaoBuscaInsrutorActionPerformed

    private void BotaoBuscaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoBuscaCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscaCurso;
    private javax.swing.JButton BotaoBuscaInsrutor;
    private javax.swing.JButton BotaoBuscaOferta;
    private javax.swing.JLabel CPFI;
    private javax.swing.JButton CadastrarCurso;
    private javax.swing.JButton CadastrarInstrutor;
    private javax.swing.JButton CadastrarOferta;
    private javax.swing.JLabel CelI;
    private javax.swing.JLabel DataF;
    private javax.swing.JLabel DataI;
    private javax.swing.JLabel EndI;
    private javax.swing.JLabel IdI;
    private javax.swing.JTextField InputBuscaCurso;
    private javax.swing.JTextField InputBuscaInstrutor;
    private javax.swing.JTextField InputBuscaOferta;
    private javax.swing.JTextField InputCPFInstrutor;
    private javax.swing.JTextField InputCargaCurso;
    private javax.swing.JTextField InputCelularInstrutor;
    private javax.swing.JTextField InputCursoOferta;
    private javax.swing.JTextField InputDataFinalOferta;
    private javax.swing.JTextField InputDataInicialOferta;
    private javax.swing.JTextField InputEmentaCurso;
    private javax.swing.JTextField InputEnderecoInstrutor;
    private javax.swing.JTextField InputIDInstrutor;
    private javax.swing.JTextField InputIDOferta;
    private javax.swing.JTextField InputIdCurso;
    private javax.swing.JTextField InputIdInstrutorOferta;
    private javax.swing.JTextField InputNomeInstrutor;
    private javax.swing.JTextField InputSituacaoOferta;
    private javax.swing.JLabel InstrutorO;
    private javax.swing.JLabel NomeI;
    private javax.swing.JTextField NomeInputCurso;
    private javax.swing.JLabel NomeO;
    private javax.swing.JLabel NomeO1;
    private javax.swing.JLabel StatusO;
    private javax.swing.JLabel cursoL;
    private javax.swing.JLabel ementaL;
    private javax.swing.JLabel hourL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
}
