
package Visao;
import Controllers.cursoontroller;
import Controllers.InstrutorController;
import Controllers.OfertaController;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Oferta;
import modelo.Curso;
import modelo.Instrutor;
import dao.JPA.CursoJpaDAO;
import dao.JPA.InstrutorJpaDAO;
import dao.JPA.OfertaJpaDAO;

/**
 *
 * @author Sullyvan Marks
 */
public class NewJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    public NewJPanel1() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        NomeI = new javax.swing.JLabel();
        CPFI = new javax.swing.JLabel();
        EndI = new javax.swing.JLabel();
        CelI = new javax.swing.JLabel();
        CadastrarInstrutor = new javax.swing.JButton();
        InputNomeInstrutor = new javax.swing.JTextField();
        InputCPFInstrutor = new javax.swing.JTextField();
        InputEnderecoInstrutor = new javax.swing.JTextField();
        InputCelularInstrutor = new javax.swing.JTextField();
        IdI = new javax.swing.JLabel();
        InputIDInstrutor = new javax.swing.JTextField();
        BotaoBuscaInsrutor = new javax.swing.JButton();
        BotaoRemoverInstrutor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        DataF = new javax.swing.JLabel();
        NomeO = new javax.swing.JLabel();
        DataI = new javax.swing.JLabel();
        StatusO = new javax.swing.JLabel();
        InstrutorO = new javax.swing.JLabel();
        CadastrarOferta = new javax.swing.JButton();
        InputIDOferta = new javax.swing.JTextField();
        InputDataInicialOferta = new javax.swing.JTextField();
        InputDataFinalOferta = new javax.swing.JTextField();
        InputSituacaoOferta = new javax.swing.JTextField();
        InputIdInstrutorOferta = new javax.swing.JTextField();
        InputCursoOferta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotaoRemoverOferta = new javax.swing.JButton();
        BotaoBuscaOferta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cursoL = new javax.swing.JLabel();
        ementaL = new javax.swing.JLabel();
        hourL = new javax.swing.JLabel();
        CadastrarCurso = new javax.swing.JButton();
        NomeInputCurso = new javax.swing.JTextField();
        InputEmentaCurso = new javax.swing.JTextField();
        InputCargaCurso = new javax.swing.JTextField();
        NomeO1 = new javax.swing.JLabel();
        InputIdCurso = new javax.swing.JTextField();
        BotaoBuscarCurso = new javax.swing.JButton();
        BotaoRemoverCurso = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        NomeI.setText("Nome:");

        CPFI.setText("CPF:");

        EndI.setText("Endereço:");

        CelI.setText("Celular");

        CadastrarInstrutor.setText("Cadastrar");
        CadastrarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarInstrutorActionPerformed(evt);
            }
        });

        InputNomeInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomeInstrutorActionPerformed(evt);
            }
        });

        IdI.setText("Id:");

        InputIDInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIDInstrutorActionPerformed(evt);
            }
        });

        BotaoBuscaInsrutor.setText("Buscar");
        BotaoBuscaInsrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaInsrutorActionPerformed(evt);
            }
        });

        BotaoRemoverInstrutor.setText("Remover");
        BotaoRemoverInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverInstrutorActionPerformed(evt);
            }
        });

        jLabel5.setText("Outras Opções");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastrarInstrutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeI)
                    .addComponent(CPFI)
                    .addComponent(EndI)
                    .addComponent(CelI)
                    .addComponent(IdI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputNomeInstrutor)
                            .addComponent(InputCPFInstrutor)
                            .addComponent(InputEnderecoInstrutor)
                            .addComponent(InputCelularInstrutor, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                        .addGap(189, 189, 189))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(InputIDInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotaoBuscaInsrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoRemoverInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(213, 213, 213))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeI)
                    .addComponent(InputNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFI)
                    .addComponent(InputCPFInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndI)
                    .addComponent(InputEnderecoInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelI)
                    .addComponent(InputCelularInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdI)
                    .addComponent(InputIDInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(CadastrarInstrutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoBuscaInsrutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRemoverInstrutor))
                .addGap(28, 28, 28))
        );

        jTabbedPane4.addTab("Cadastrar novo Instrutor", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane1.addTab("Instrutor", jPanel1);

        DataF.setText("Data Final:");

        NomeO.setText("Id:");

        DataI.setText("Data Inicial:");

        StatusO.setText("Situação Oferta:");

        InstrutorO.setText("Instrutor:");

        CadastrarOferta.setText("Cadastrar");
        CadastrarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarOfertaActionPerformed(evt);
            }
        });

        InputIDOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIDOfertaActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso:");

        BotaoRemoverOferta.setText("Remover");
        BotaoRemoverOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverOfertaActionPerformed(evt);
            }
        });

        BotaoBuscaOferta.setText("Buscar");
        BotaoBuscaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaOfertaActionPerformed(evt);
            }
        });

        jLabel6.setText("Outras Opções");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CadastrarOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NomeO)
                                        .addGap(96, 96, 96)
                                        .addComponent(InputIDOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(StatusO)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(InputCursoOferta)
                                            .addComponent(InputDataFinalOferta)
                                            .addComponent(InputDataInicialOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(InputSituacaoOferta, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(InstrutorO)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputIdInstrutorOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(DataI)
                            .addComponent(DataF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BotaoRemoverOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoBuscaOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(InputIDOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeO))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataI)
                    .addComponent(InputDataInicialOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataF)
                            .addComponent(InputDataFinalOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(BotaoRemoverOferta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusO)
                    .addComponent(InputSituacaoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCursoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstrutorO)
                    .addComponent(InputIdInstrutorOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(CadastrarOferta)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Cadastrar nova oferta", jPanel3);

        jTabbedPane1.addTab("Oferta", jTabbedPane3);

        cursoL.setText("Nome:");

        ementaL.setText("Ementa:");

        hourL.setText("Carga Horária:");

        CadastrarCurso.setText("Cadastrar");
        CadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarCursoActionPerformed(evt);
            }
        });

        NomeO1.setText("Id:");

        InputIdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIdCursoActionPerformed(evt);
            }
        });

        BotaoBuscarCurso.setText("Buscar");
        BotaoBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarCursoActionPerformed(evt);
            }
        });

        BotaoRemoverCurso.setText("Remover");
        BotaoRemoverCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverCursoActionPerformed(evt);
            }
        });

        jLabel7.setText("Outras Opções");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CadastrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(BotaoRemoverCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(hourL)
                                .addGap(85, 85, 85)
                                .addComponent(InputCargaCurso))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ementaL)
                                .addGap(18, 18, 18)
                                .addComponent(InputEmentaCurso))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cursoL)
                                .addGap(27, 27, 27)
                                .addComponent(NomeInputCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addComponent(NomeO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(215, 215, 215))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NomeO1)
                        .addComponent(InputIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cursoL)
                        .addComponent(NomeInputCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ementaL)
                    .addComponent(InputEmentaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourL)
                    .addComponent(InputCargaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(CadastrarCurso)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRemoverCurso)
                    .addComponent(BotaoBuscarCurso))
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Cadastrar novo curso", jPanel2);

        jTabbedPane1.addTab("Curso", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        });
    }
    
    private void CadastrarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarOfertaActionPerformed
      
            
            Oferta oferta = new Oferta();
            
            oferta.setId(Long.parseLong(InputIDOferta.getText()));
            oferta.setDataInicial(InputDataInicialOferta.getText());
            oferta.setDataFinal(InputDataFinalOferta.getText());
            oferta.setStatus(Integer.parseInt(InputSituacaoOferta.getText()));
            oferta.setCurso(Long.parseLong(InputCursoOferta.getText()));
            oferta.setInstrutor(Long.parseLong(InputIdInstrutorOferta.getText()));
            OfertaJpaDAO.getInstance().merge(oferta);
            
            JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
            System.out.println("cadastrado com sucesso!");
            InputIDOferta.setText("");
            InputDataInicialOferta.setText("");
            InputDataFinalOferta.setText("");
            InputSituacaoOferta.setText("");
            InputCursoOferta.setText("");
            InputIdInstrutorOferta.setText("");
                
         
      
    }//GEN-LAST:event_CadastrarOfertaActionPerformed

    private void InputIDOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIDOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIDOfertaActionPerformed

    private void InputNomeInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomeInstrutorActionPerformed
   
               
    }//GEN-LAST:event_InputNomeInstrutorActionPerformed

    private void CadastrarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarInstrutorActionPerformed
        Instrutor instrutor = new Instrutor();
    instrutor.setNome(InputNomeInstrutor.getText());
    instrutor.setId(Long.parseLong(InputIDInstrutor.getText()));
    instrutor.setCpf(InputCPFInstrutor.getText());
    instrutor.setEndereco(InputEnderecoInstrutor.getText());
    instrutor.setCelular(InputCelularInstrutor.getText());
    InstrutorJpaDAO.getInstance().merge(instrutor);
    
    JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
    
       InputNomeInstrutor.setText("");
       InputIDInstrutor.setText("");
       InputCPFInstrutor.setText("");
       InputEnderecoInstrutor.setText("");
       InputCelularInstrutor.setText("");
    }//GEN-LAST:event_CadastrarInstrutorActionPerformed

    private void InputIDInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIDInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIDInstrutorActionPerformed

    private void BotaoBuscaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaOfertaActionPerformed
        // TODO add your handling code here:
           Long id = Long.parseLong(JOptionPane.showInputDialog("Digite o id"));
           Oferta oferta = OfertaJpaDAO.getInstance().getById(id);
            InputIDOferta.setText(String.valueOf(oferta.getId()));
            InputDataInicialOferta.setText(String.valueOf(oferta.getDataInicial()));
            InputDataFinalOferta.setText(oferta.getDataFinal());
            InputSituacaoOferta.setText(String.valueOf(oferta.getStatus()));
            InputCursoOferta.setText(String.valueOf(oferta.getCurso()));
            InputIdInstrutorOferta.setText(String.valueOf(oferta.getInstrutor()));
      
            
    }//GEN-LAST:event_BotaoBuscaOfertaActionPerformed

    private void BotaoBuscaInsrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaInsrutorActionPerformed
            Long id = Long.parseLong(JOptionPane.showInputDialog("Digite o id"));
           Instrutor instrutor = InstrutorJpaDAO.getInstance().getById(id);
           InputNomeInstrutor.setText((instrutor.getNome()));
            InputCPFInstrutor.setText(instrutor.getCpf());
            InputEnderecoInstrutor.setText(instrutor.getEndereco());
            InputCelularInstrutor.setText(instrutor.getCelular());
            
         JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
       
         
       
    }//GEN-LAST:event_BotaoBuscaInsrutorActionPerformed

    private void BotaoRemoverInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverInstrutorActionPerformed
      Long id = Long.parseLong(JOptionPane.showInputDialog("Digite o id"));
        InstrutorJpaDAO.getInstance().removeById(id);
        JOptionPane.showMessageDialog(this, "Removido com sucesso !");
    }//GEN-LAST:event_BotaoRemoverInstrutorActionPerformed

    private void BotaoRemoverOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverOfertaActionPerformed
        Long id = Long.parseLong(JOptionPane.showInputDialog("Digite o id"));
        OfertaJpaDAO.getInstance().removeById(id);
        JOptionPane.showMessageDialog(this, "Removido com sucesso !");
    }//GEN-LAST:event_BotaoRemoverOfertaActionPerformed

    private void BotaoRemoverCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverCursoActionPerformed
        Long id = Long.parseLong(JOptionPane.showInputDialog("Digite o id"));
        CursoJpaDAO.getInstance().removeById(id);
        JOptionPane.showMessageDialog(this, "Removido com sucesso !");
    }//GEN-LAST:event_BotaoRemoverCursoActionPerformed

    private void BotaoBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarCursoActionPerformed

        Long id = Long.parseLong(JOptionPane.showInputDialog("Digite o id"));
        Curso curso = CursoJpaDAO.getInstance().getById(id);
        InputIdCurso.setText(String.valueOf(curso.getId()));
        NomeInputCurso.setText(curso.getNome());
        InputEmentaCurso.setText(curso.getEmenta());
        InputCargaCurso.setText(curso.getCargaHoraria());

        System.out.println(InputIdCurso);
        System.out.println(NomeInputCurso);
        System.out.println(InputEmentaCurso);
        System.out.println(InputCargaCurso);

        JOptionPane.showMessageDialog(this, "Salvo com sucesso !");

    }//GEN-LAST:event_BotaoBuscarCursoActionPerformed

    private void InputIdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIdCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIdCursoActionPerformed

    private void CadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarCursoActionPerformed

        Curso curso = new Curso();

        curso.setId(Long.parseLong(InputIdCurso.getText()));
        curso.setNome(NomeInputCurso.getText());
        curso.setEmenta(InputEmentaCurso.getText());
        curso.setCargaHoraria(InputCargaCurso.getText());
        CursoJpaDAO.getInstance().merge(curso);

        JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
        InputIdCurso.setText("");
        NomeInputCurso.setText("");
        InputEmentaCurso.setText("");
        InputCargaCurso.setText("");
    }//GEN-LAST:event_CadastrarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscaInsrutor;
    private javax.swing.JButton BotaoBuscaOferta;
    private javax.swing.JButton BotaoBuscarCurso;
    private javax.swing.JButton BotaoRemoverCurso;
    private javax.swing.JButton BotaoRemoverInstrutor;
    private javax.swing.JButton BotaoRemoverOferta;
    private javax.swing.JLabel CPFI;
    private javax.swing.JButton CadastrarCurso;
    private javax.swing.JButton CadastrarInstrutor;
    private javax.swing.JButton CadastrarOferta;
    private javax.swing.JLabel CelI;
    private javax.swing.JLabel DataF;
    private javax.swing.JLabel DataI;
    private javax.swing.JLabel EndI;
    private javax.swing.JLabel IdI;
    private javax.swing.JTextField InputCPFInstrutor;
    private javax.swing.JTextField InputCargaCurso;
    private javax.swing.JTextField InputCelularInstrutor;
    private javax.swing.JTextField InputCursoOferta;
    private javax.swing.JTextField InputDataFinalOferta;
    private javax.swing.JTextField InputDataInicialOferta;
    private javax.swing.JTextField InputEmentaCurso;
    private javax.swing.JTextField InputEnderecoInstrutor;
    private javax.swing.JTextField InputIDInstrutor;
    private javax.swing.JTextField InputIDOferta;
    private javax.swing.JTextField InputIdCurso;
    private javax.swing.JTextField InputIdInstrutorOferta;
    private javax.swing.JTextField InputNomeInstrutor;
    private javax.swing.JTextField InputSituacaoOferta;
    private javax.swing.JLabel InstrutorO;
    private javax.swing.JLabel NomeI;
    private javax.swing.JTextField NomeInputCurso;
    private javax.swing.JLabel NomeO;
    private javax.swing.JLabel NomeO1;
    private javax.swing.JLabel StatusO;
    private javax.swing.JLabel cursoL;
    private javax.swing.JLabel ementaL;
    private javax.swing.JLabel hourL;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
}
