-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 10:38:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NULL,
  `atribuicoes` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Setor` (
  `idSetor` INT NOT NULL AUTO_INCREMENT,
  `nome_setor` VARCHAR(45) NULL,
  `Gerente_id` INT NOT NULL,
  PRIMARY KEY (`idSetor`),
  INDEX `fk_Setor_Funcionario1_idx` (`Gerente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Setor_Funcionario1`
    FOREIGN KEY (`Gerente_id`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `data_admisao` VARCHAR(10) NULL,
  `data_recisao` VARCHAR(10) NULL,
  `Cargo_id` INT NOT NULL,
  `Setor_idSetor` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Funcionario_Cargo_idx` (`Cargo_id` ASC) VISIBLE,
  INDEX `fk_Funcionario_Setor1_idx` (`Setor_idSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Cargo`
    FOREIGN KEY (`Cargo_id`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `mydb`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
