# -*- coding: utf-8 -*-
"""Segredo do Cofre - Sullyvan Marks

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JMAn_0TasDqSukDhYT6Xg4w_z6rAbDdf

### NOME: Sullyvan Marks Nascimento De Oliveira

### Funções
"""

import numpy
import numpy as np
import random

def CriarPartida():
  global senha
  global partida
  partida = numpy.zeros((14,4), dtype=int)
  senha = np.random.permutation(random.sample(range(0, 9), 4))

def Partida():
  global senha
  global partida
  global nome
  global contadorPonto
  

  contador = 0
  contadorPonto = 10
  LinhaDica = -1
  LinhaPalpite = -2
  nome = input("Qual é o seu nome?")
  

    

  while contador < 7:

    dica = list()
    palpite = int(input("\nInsira 4 números, sem repetição:"))
    print('_________________________________________________\n')

      # Divisor de cada número do palpite para 
    p1 = palpite // 1000 % 10
    p2 = palpite // 100 % 10
    p3 = palpite // 10 %10
    p4 = palpite // 1 % 10
    


      # Verifica se os valores de palpite estão diferentes
    if p1 != p2 and p1 != p3 and p1 != p4:
      if p2 != p3 and p2 != p4:
        if p3 != p4:
                
      # comparação de valores de senha e palpite para adicionar as dicas
          if p1 in senha and p1 != senha[0]:
            dica1 = -1
            dica.append(dica1)

          elif p1 in senha and p1 == senha[0]:
            dica1 = 1
            dica.append(dica1)

          elif p1 not in senha:
            dica1 = 0
            dica.append(dica1)

          if p2 in senha and p2 != senha[1]:
            dica2 = -1
            dica.append(dica2)

          elif p2 in senha and p2 == senha[1]:
            dica2 = 1
            dica.append(dica2)

          elif p2 not in senha:
            dica2 = 0
            dica.append(dica2)

          if p3 in senha and p3 != senha[2]:
            dica3 = -1
            dica.append(dica3)

          elif p3 in senha and p3 == senha[2]:
            dica3 = 1
            dica.append(dica3)

          elif p3 not in senha:
            dica3 = 0
            dica.append(dica3)

          if p4 in senha and p4 != senha[3]:
            dica4 = -1
            dica.append(dica4)

          elif p4 in senha and p4 == senha[3]:
            dica4 = 1
            dica.append(dica4)

          elif p4 not in senha:
            dica4 = 0
            dica.append(dica4)


      # Contadores       
        contador += 1 
        contadorPonto -= 1
        LinhaDica +=2
        LinhaPalpite +=2

      # Adiciona o palpite e a dica na partida
      partida[LinhaDica, :] =  dica
      partida[LinhaPalpite, 0] = p1
      partida[LinhaPalpite, 1] = p2  
      partida[LinhaPalpite, 2] = p3  
      partida[LinhaPalpite, 3] = p4
      
      # print do palpite e da dica
      print(f'Palpite número {contador}:')
      print(f'{p1} {p2} {p3} {p4}')         
      print(f'{dica[0]} {dica[1]} {dica[2]} {dica[3]}')

        # Condições de acerto ou erro
      if p1 == senha[0] and p2 == senha[1] and p3 == senha[2] and p4 == senha[3]:
        print(f'Parabéns, você acertou!\n Sua pontuação: {contadorPonto}')
        
        break
      if contador == 7:
        if p1 != senha[0] or p2 != senha[1] or p3 != senha[2] or p4 != senha[3]:
          contadorPonto = 0
          print(f'Fim de Jogo!\n A senha era: {senha}\n Sua pontuação: {contadorPonto}')
        break

"""### Interface"""

listaJogadores = []
  
while True:
 
  
  try:
    print('SEGREDO DO COFRE - MENU:')
    print('Opção 1: Jogar uma partida: ')
    print('Opção 0: Sair do Programa')
    opcao = int(input('Qual a sua Opção: '))
    if opcao == 0:
      print('TCHAU!!! - ATÉ A PRÓXIMA')
      break
    elif (opcao != 1 and opcao != 0):
      print('Opcao Incorreta. Escolha de novo.')
    else:
      print('Qual é o Segredo?')
      segredo = CriarPartida()
      Palpite = Partida()
      jogador = [nome, contadorPonto, partida]
      listaJogadores.append(jogador)
      
  except Exception as erro:
    print(f'Erro: {erro}')

import pandas
últimaPartida = pandas.DataFrame(partida, 
                            index=['PALPITE 1', 'DICA 1', 'PALPITE 2', 'DICA 2','PALPITE 3', 'DICA 3', 'PALPITE 4', 'DICA 4','PALPITE 5', 'DICA 5', 'PALPITE 6', 'DICA 6', 'PALPITE 7', 'DICA 7' ], 
                          columns=['N°1', 'N°2', 'N°3','N°4'])
últimaPartida

def Historico():
  global nome
  global contadorPonto
  global partida
  for index, x, in enumerate(listaJogadores):
    print(f'nome do jogador {index + 1}: {x[0]}')
    print(f'Pontuação do jogador: {x[1]}')
    print(f'Partida:\n{x[2]}')
    print("_____________________\n")
 
Historico()